DROP FUNCTION IF EXISTS insert_into_episode(CHARACTER, date, integer, integer, integer, integer, integer);

DROP FUNCTION IF EXISTS insert_into_season(integer, integer);

DROP FUNCTION IF EXISTS insert_into_serial(CHARACTER, INTEGER, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_person(CHARACTER, DATE, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_director(INTEGER);

DROP FUNCTION IF EXISTS insert_into_director(CHARACTER, DATE, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_creator(INTEGER);

DROP FUNCTION IF EXISTS insert_into_creator(CHARACTER, DATE, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_writer(INTEGER);

DROP FUNCTION IF EXISTS insert_into_writer(CHARACTER, DATE, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_actor(INTEGER);

DROP FUNCTION IF EXISTS insert_into_actor(CHARACTER, DATE, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_actor_award(CHARACTER);

DROP FUNCTION IF EXISTS insert_into_app_user(CHARACTER, INTEGER, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_comments(DATE, CHARACTER, CHARACTER, INTEGER, INTEGER);

DROP FUNCTION IF EXISTS insert_into_creates(INTEGER, INTEGER);

DROP FUNCTION IF EXISTS insert_into_directs(INTEGER, INTEGER, INTEGER, INTEGER);

DROP FUNCTION IF EXISTS insert_into_films(INTEGER, INTEGER, INTEGER,INTEGER);

DROP FUNCTION IF EXISTS insert_into_genre(CHARACTER);

DROP FUNCTION IF EXISTS insert_into_plays(INTEGER, INTEGER);

DROP FUNCTION IF EXISTS insert_into_reviews(CHARACTER, INTEGER, CHARACTER, CHARACTER, DATE);

DROP FUNCTION IF EXISTS insert_into_role(CHARACTER);

DROP FUNCTION IF EXISTS insert_into_role_has_award(INTEGER, CHARACTER, INTEGER,INTEGER, INTEGER, INTEGER);

DROP FUNCTION IF EXISTS insert_into_serial_award(CHARACTER);

DROP FUNCTION IF EXISTS insert_into_serial_has_award(INTEGER, CHARACTER, INTEGER);

DROP FUNCTION IF EXISTS insert_into_serial_has_genre(INTEGER, CHARACTER);

DROP FUNCTION IF EXISTS insert_into_subscribes(CHARACTER, INTEGER);

DROP FUNCTION IF EXISTS insert_into_writes(INTEGER, INTEGER, INTEGER, INTEGER);

DROP TABLE IF EXISTS serial CASCADE;

DROP TABLE IF EXISTS genre CASCADE;

DROP TABLE IF EXISTS serial_has_genre CASCADE;

DROP TABLE IF EXISTS app_user CASCADE;

DROP TABLE IF EXISTS subscribes CASCADE;

DROP TABLE IF EXISTS reviews CASCADE;

DROP TABLE IF EXISTS season CASCADE;

DROP TABLE IF EXISTS comments CASCADE;

DROP TABLE IF EXISTS episode CASCADE;

DROP TABLE IF EXISTS person CASCADE;

DROP TABLE IF EXISTS director CASCADE;

DROP TABLE IF EXISTS writer CASCADE;

DROP TABLE IF EXISTS creator CASCADE;

DROP TABLE IF EXISTS actor CASCADE;

DROP TABLE IF EXISTS role CASCADE;

DROP TABLE IF EXISTS plays CASCADE;

DROP TABLE IF EXISTS films CASCADE;

DROP TABLE IF EXISTS creates CASCADE;

DROP TABLE IF EXISTS directs CASCADE;

DROP TABLE IF EXISTS writes CASCADE;

DROP TABLE IF EXISTS actor_award CASCADE;

DROP TABLE IF EXISTS serial_award CASCADE;

DROP TABLE IF EXISTS role_has_award CASCADE;

DROP TABLE IF EXISTS serial_has_award CASCADE;
