DROP TABLE serial CASCADE;

DROP TABLE genre CASCADE;

DROP TABLE serial_has_genre CASCADE;

DROP TABLE app_user CASCADE;

DROP TABLE subscribes CASCADE;

DROP TABLE reviews CASCADE;

DROP TABLE season CASCADE;

DROP TABLE comments CASCADE;

DROP TABLE episode CASCADE;

DROP TABLE person CASCADE;

DROP TABLE director CASCADE;

DROP TABLE writer CASCADE;

DROP TABLE creator CASCADE;

DROP TABLE actor CASCADE;

DROP TABLE role CASCADE;

DROP TABLE plays CASCADE;

DROP TABLE films CASCADE;

DROP TABLE creates CASCADE;

DROP TABLE directs CASCADE;

DROP TABLE writes CASCADE;

DROP TABLE actor_award CASCADE;

DROP TABLE serial_award CASCADE;

DROP TABLE role_has_award CASCADE;

DROP TABLE serial_has_award CASCADE;
